# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Matt/thesis/vivado/thesis.srcs/sources_1/ip/clk_master/clk_master.xci
# IP: The module: 'clk_master' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matt/thesis/vivado/thesis.gen/sources_1/ip/clk_master/clk_master_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_master'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Matt/thesis/vivado/thesis.gen/sources_1/ip/clk_master/clk_master.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_master'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Matt/thesis/vivado/thesis.gen/sources_1/ip/clk_master/clk_master_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_master'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Matt/thesis/vivado/thesis.srcs/sources_1/ip/clk_master/clk_master.xci
# IP: The module: 'clk_master' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matt/thesis/vivado/thesis.gen/sources_1/ip/clk_master/clk_master_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_master'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Matt/thesis/vivado/thesis.gen/sources_1/ip/clk_master/clk_master.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_master'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Matt/thesis/vivado/thesis.gen/sources_1/ip/clk_master/clk_master_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_master'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
